# Problem 2
#
# Problem Statement
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.



# Initialize the first two Fibonacci numbers: F₁ = 1, F₂ = 2
a, b = 1, 2

# Sum of even-valued Fibonacci terms
total = 0

# Continue looping while the current Fibonacci number (a) does not exceed 4 million
while a <= 4_000_000:
    # Check if the current Fibonacci number is even
    if a % 2 == 0:
        # If even, add it to the running total
        total += a
    
    # Update a and b to the next pair in the Fibonacci sequence:
    # - a becomes the next term (previous b)
    # - b becomes the new next term (a + b, i.e., sum of previous two)
    a, b = b, a + b

# After the loop, print the sum of all even Fibonacci numbers ≤ 4,000,000
print(total)  # Expected output: 4613732